#!/bin/sh

sudo echo -n ""

# Move every workspace except the one named DO_NOT_MOVE_WS_NAME from
# the left monitor to the right monitor
DO_NOT_MOVE_WS_NAME="10:"

outputs=$(i3-msg -t get_outputs | jq -r '.[] | select(.active)')
left_output=$(echo "$outputs" \
                  | jq -r 'select(.rect.x == 0) | .name')
right_output=$(echo "$outputs" \
                  | jq -r 'select(.rect.x != 0) | .name')

to_move=$(i3-msg -t get_workspaces \
              | jq -r ".[] | select(.output == \"$right_output\" and .name != \"$DO_NOT_MOVE_WS_NAME\") | .name")
for w in $to_move; do
    echo "workspace $w, move workspace to output $left_output"
    i3-msg "workspace $w, move workspace to output $left_output"
done

pkill redshift

sudo virsh start win10

looking-glass-client &
